version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - '16379:6379'
    ulimits:
      memlock: -1
